[package]
name = "rust-service"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
url = "2.3"
hyper_wasi = { version = "0.15", features = ["full"] }
tokio_wasi = { version = "1", features = ["io-util", "fs", "net", "time", "rt", "macros"] }
